site_name: Napolitan
site_url: https://i2y.github.io/napolitan
repo_url: https://github.com/i2y/napolitan
theme:
  name: material
  language: "en"
  logo: "food_spaghetti_neapolitan.png"
  favicon: "food_spaghetti_neapolitan.png"
  features:
    # - navigation.tabs
    - navigation.top
    - navigation.footer
    - content.code.annotate

  palette:
    primary: custom

  font:
    text: "Roboto"
    code: "Roboto Mono"
  icon:
    repo: fontawesome/brands/github
copyright: "&copy; 2024 Yasushi Itoh"
repo_name: i2y/napolitan
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - License: license.md
plugins:
  search:
    lang: 'en'

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - admonition
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://x.com/i2y_
      name: i2y on X
    - icon: fontawesome/brands/github
      link: https://github.com/i2y/napolitan/
  files:
    - examples/*
